[target.http_dll]
type = "shared"
sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include", "kthook/include" ]
compile-features = ["cxx_std_20"]
link-libraries = ["kthook"]

[subdir.kthook]